#define ATAUTH_DEFAULT_FIRST_APP_NAME "firstApp"
#define ATAUTH_DEFAULT_FIRST_DEVICE_NAME "firstDevice"
#define ATAUTH_AES_256_KEY_BYTES 32
#define ATAUTH_RSA_2048_PRIVKEY_BYTES 1300 // in PKCS#8 format includes padding

#define ATAUTH_DEFAULT_APKAM_RETRY_INTERVAL 10 // seconds
#define ATAUTH_MAX_APKAM_AUTH_RETRY_ATTMEPTS 10
#define ATAUTH_ENROLLMENT_DENIED_ERR_CODE "error:AT0025"
#define ATAUTH_ENROLLMENT_PENDING_ERR_CODE "error:AT0026"

#define ATAUTH_ENCRYPTED_DEFAULT_ENC_PRIVKEY_NAME "default_enc_private_key"
#define ATAUTH_ENCRYPTED_SELF_ENC_KEY_NAME "default_self_enc_key"