name: Build Source Tests
on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  atsdk:
    strategy:
      fail-fast: true
      matrix:
        include:
          - cc: "gcc"
            cflags: "-std=c99 -Wall -Wextra -Werror-implicit-function-declaration"
          - cc: "clang"
            cflags: "-std=c99 -Wall -Wextra -Werror-implicit-function-declaration"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        # Pin cmake to <4.0.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@3a6cbe35ba64df7ca70c51365c4aff65db9a9037 # v2.1.1
        with:
          cmake-version: "3.31.10"

      - name: Show tooling versions
        run: |
          echo ${{ matrix.cc }} version
          ${{ matrix.cc }} --version
          echo cmake version
          cmake --version

      - name: Install atsdk
        run: cmake -S . -B build -DCMAKE_C_COMPILER="${{ matrix.cc }}" \
          -DCMAKE_C_FLAGS="${{ matrix.cflags }}" \
          -DCMAKE_COMPILE_WARNING_AS_ERROR="on"

      - name: Show CMake Cache Variables
        run: cmake -L -N -S . -B build

      - name: Build atsdk
        run: cmake --build build

      - name: Install atsdk
        run: sudo cmake --build build --target install

      - name: Build sample_cmake_project
        working-directory: examples/desktop/sample_cmake_project
        run: |
          cmake -S . -B build -Datsdk="/usr/local/bin/cmake/atsdk"
          cmake --build build

      - name: Run sample_cmake_project executable
        working-directory: examples/desktop/sample_cmake_project
        run: |
          ./build/main

  atsdk-package:
    strategy:
      fail-fast: true
      matrix:
        preset: ["package-static", "package-source"]
    runs-on: "ubuntu-latest"
    steps:
      # Pin cmake to <4.0.0
      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@3a6cbe35ba64df7ca70c51365c4aff65db9a9037 # v2.1.1
        with:
          cmake-version: "3.31.10"
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: cmake --workflow --preset ${{ matrix.preset }}
