name: C_Release_Automation

on:
  push:
    tags:
      - "v*.*.*"

permissions: # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  source_tarball:
    name: Generate source tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Create tarball
        run: |
          mkdir tarball
          mkdir at_c-${{ github.ref_name }}
          cp -R packages/* at_c-${{ github.ref_name }}
          tar -cvzf tarball/at_c-${{ github.ref_name }}.tar.gz at_c-${{ github.ref_name }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: csshnpd-src-${{github.ref_name}}-${{github.run_number}}-${{github.run_attempt}}
          path: ./tarball/at_c-${{ github.ref_name }}.tar.gz

  github-release:
    name: >-
      Upload artifacts and generate checksums for provenance
    needs: [source_tarball]
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    permissions:
      contents: write # IMPORTANT: mandatory for making GitHub Releases
      id-token: write # IMPORTANT: mandatory for sigstore
      attestations: write
    steps:
      - name: Download all the tarballs
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          path: tarballs/
      - name: Move packages for signing
        run: |
          cd tarballs
          mv */*.tar.gz .
          rm -Rf -- */
      - name: Generate SBOM
        uses: sbomify/github-action@8ea6f28cd562edee2665001cd4f17aaf7a283722 # v0.5.0
        env:
          TOKEN: ${{ secrets.SBOMIFY_TOKEN }}
          COMPONENT_ID: '-93khk8pUi'
          LOCK_FILE: './tools/conan.lock'
          SBOM_VERSION: ${{github.ref_name}}
          OUTPUT_FILE: 'tarballs/at_c-${{github.ref_name}}-sbom.cdx.json'
          AUGMENT: true
          ENRICH: true
          UPLOAD: true
      - name: Generate SHA256 checksums
        working-directory: tarballs
        run: sha256sum * > checksums.txt
      - name: Upload artifacts to GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release upload '${{ github.ref_name }}' tarballs/** --repo '${{
          github.repository }}'
      - id: hash
        name: Pass artifact hashes for SLSA provenance
        working-directory: tarballs
        run: |
          echo "hashes=$(cat checksums.txt | base64 -w0)" >> "$GITHUB_OUTPUT"
      - uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
        with:
          subject-path: "tarballs/**"

  provenance:
    needs: [github-release]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write # Needed for release uploads
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0 # 5a775b367a56d5bd118a224a811bba288150a563
    with:
      base64-subjects: "${{ needs.github-release.outputs.hashes }}"
      upload-assets: true
